version: '3'

services:
  frontend_preprod:
    build:
      context: .
      dockerfile: ./dockerfiles/production/Dockerfile
    container_name: frontend_preprod
    restart: always
    expose:
      - 80
    environment:
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=recipe.preprod.nonstopintegration.ml
      - LETSENCRYPT_HOST=recipe.preprod.nonstopintegration.ml
      - LETSENCRYPT_EMAIL=nonstopintegration@gmail.com

networks:
  default:
    external:
      name: webproxy
